### ISSUE TITLE
APRS tracker without GPS module

### ISSUE THREAD

**Issue by cookins** [billygr/arduino-aprs-tracker#2]
Hey there!
Im not exactly programmer, so can somebody help me to edit code for manual GPS coords just.
For me its not necessary to update GPS coords, cuz device located in same spot all time.
Thank you.

**Comment by billygr** [comment]
Looking at the code you will need a lot of changes, do you need just one update or updates over fixed intervals ?

**Comment by cookins** [comment]
just fixed coords. for all time stationary location.
without GPS module of course.

**Comment by billygr** [comment]
Here you go compile test only
https://github.com/billygr/aprs-tracker-without-gps-module

**Comment by cookins** [comment]
Thank you :kissing_heart:
