### ISSUE TITLE
How to change aprs beacon timer? 

### ISSUE THREAD

**Issue by kovalroma** [billygr/arduino-aprs-tracker#5]
Hello, 
I found that tracker send beacon every 1 minutes. 
Is it possible to change it to 30 seconds ? 
I've changed this line
```
 #define TIMER_MINUTES 30L*1000L
```
But it didn't help.

**Comment by billygr** [comment]
Hi ,

you can change directly the interval on this line

aprs_update_timer_id=timer.setInterval(2*TIMER_MINUTES, setAprsUpdateFlag)

Replace 2*TIMER_MINUTES with 30000. I would recommend to go so low , it is way to fast and you will fill the APRS network with messages

**Comment by kovalroma** [comment]
Thank you so much!
