### ISSUE TITLE
SmartBeaconing works ? 

### ISSUE THREAD

**Issue by kovalroma** [billygr/arduino-aprs-tracker#7]
Hello, 
We use your code for more than 1 year and very happy about it. 
Today I found "SmartBeaconing" in your code. Does it work ? Do I need some special configuration to enable it ? 
Or it enabled by default ?

**Comment by billygr** [comment]
Thanks !!!, it's not enabled, was part of a code to integrated it. One of a fellow user on github just created a pull with smartbeaconing, will do some test and merge it over the weekend

**Comment by billygr** [comment]
Integrated into smartbeaconing branch, update also the libAPRS and report :)

**Comment by kovalroma** [comment]
Thank you so much!
